add model book, add table users_books, add migration
RusBiblicalChurch/ChristianBook pull request #4
Opened 2018-03-02 08:50 UTC by isabloCh

2018-03-02 15:59 UTC, resivalex requested changes

2018-03-02 15:59 UTC, resivalex commented on app/helpers/books_helper.rb
> +module BooksHelper
автоматический файл? лучше его удалить или оставить пустым как сейчас

2018-03-02 15:59 UTC, resivalex commented on db/migrate/20180301143958_add_table_users_boks.rb
> +  	create_table :users_books, id: false do |t|
мы говорили про `ordered_books`. поменяй

2018-03-02 15:59 UTC, resivalex commented on app/models/user.rb
> +	 has_and_belongs_to_many :books
`has_and_belongs_to_many :books, through: :ordered_books`

2018-03-02 15:59 UTC, resivalex commented on db/schema.rb
> +    t.boolean "recommended_rbc", default: false
что означает это название? непонятно

2018-03-05 07:36 UTC, isabloCh commented on app/helpers/books_helper.rb
> +module BooksHelper
чесслово не знаю откуда он взялся

2018-03-05 08:05 UTC, Loremaster requested changes

2018-03-05 08:05 UTC, Loremaster commented on db/migrate/20180301143958_add_table_users_boks.rb
> +  		t.belongs_to :user, index: true
You need foreign key

2018-03-05 08:05 UTC, Loremaster commented on db/migrate/20180301143958_add_table_users_boks.rb
> +  		t.belongs_to :book, index: true
you need foreign key here too

2018-03-05 08:08 UTC, resivalex commented on db/migrate/20180301143958_add_table_users_boks.rb
> +  		t.belongs_to :user, index: true
Who cares? 😃

2018-03-06 16:14 UTC, resivalex commented on app/models/user.rb
> +	 has_and_belongs_to_many :books
?

2018-03-07 12:05 UTC, resivalex approved these changes

2018-03-07 13:04 UTC, Loremaster approved these changes

2018-03-07 13:07 UTC, merged