Add price to book
RusBiblicalChurch/ChristianBook pull request #8
Opened 2018-04-17 17:40 UTC by isabloCh

Add column "price" to book, output in the operator interface and the book list

2018-04-17 23:12 UTC, resivalex requested changes

2018-04-17 23:12 UTC, resivalex commented on .vscode/launch.json
> +}
перевод каретки

2018-04-17 23:12 UTC, resivalex commented on .vscode/launch.json
> +    // Для получения дополнительной информации посетите: https://go.microsoft.com/fwlink/?linkid=830387
этот файл нужно добавить в `.gitignore`

2018-04-17 23:12 UTC, resivalex commented on app/javascript/packs/application.js
> +import './application_vue';
перевод каретки

2018-04-17 23:12 UTC, resivalex commented on app/javascript/packs/vue/book_info.vue
> +
перевод каретки

2018-04-17 23:12 UTC, resivalex commented on app/javascript/packs/vue/books_list.vue
> +</style>
перевод каретки

2018-04-17 23:12 UTC, resivalex commented on config/webpack/environment.js
> +module.exports = environment
перевод каретки

2018-04-17 23:12 UTC, resivalex commented on app/javascript/packs/vue/book_info.vue
> +<!--       <div class="book-id">{{book.id}}</div>
удалить

2018-04-17 23:12 UTC, resivalex commented on app/javascript/packs/vue/book_info.vue
> +      <h3>{{book.title}}</h3>
book_list, book_info. какой-то файл лишний

2018-04-18 08:59 UTC, resivalex commented on app/javascript/packs/vue/book_info.vue
> +      <h3>{{book.title}}</h3>
а нет. показалось

2018-04-18 10:52 UTC, isabloCh commented on .vscode/launch.json
> +    // Для получения дополнительной информации посетите: https://go.microsoft.com/fwlink/?linkid=830387
done

2018-04-18 10:55 UTC, resivalex requested changes

2018-04-18 10:55 UTC, resivalex commented on .vscode/launch.json
> +    // Для получения дополнительной информации посетите: https://go.microsoft.com/fwlink/?linkid=830387
а удалить его из гита?

2018-04-18 10:55 UTC, resivalex commented on .gitignore
> +.vscode/launch.json
перенос строки

2018-04-18 11:02 UTC, resivalex commented on config/webpacker.yml
> -    - .vue
если это вернуть, то не нужно будет указывать расширение в импорте. лучше вернуть

2018-04-18 11:05 UTC, Loremaster requested changes

2018-04-18 11:05 UTC, Loremaster commented on app/javascript/packs/application_vue.js
> +    render: h => h(BooksList)
In my opinion there is more readable way to render this component: 

```js
new Vue({
  el: "#id",
  template: `<YourComponent/>`,
  components: { YourComponent }
});
```

2018-04-18 11:05 UTC, Loremaster commented on app/javascript/packs/vue/book_info.vue
> +<script >
You need to remove space before `>`

2018-04-18 11:05 UTC, Loremaster commented on app/javascript/packs/vue/books_list.vue
> +      <book-info v-for="book in books" :key="book.id"
You should use self closing tag here since you don't show any text inside `book-info`

2018-04-18 11:05 UTC, Loremaster commented on app/javascript/packs/vue/books_list.vue
>        let el = document.getElementById('books_list');
This is incorrect way to work with input data. You need to pass `books` prop here to that component.

2018-04-18 11:07 UTC, resivalex commented on app/javascript/packs/application_vue.js
> +    render: h => h(BooksList)
👍

2018-04-18 11:09 UTC, isabloCh commented on app/javascript/packs/vue/books_list.vue
>        let el = document.getElementById('books_list');
мы вроде решили что переход на axios будет следующим шагом?

2018-04-18 11:11 UTC, resivalex commented on app/javascript/packs/vue/books_list.vue
>        let el = document.getElementById('books_list');
There is nothing about retrieving data

2018-04-18 11:18 UTC, Loremaster commented on app/javascript/packs/vue/books_list.vue
>        let el = document.getElementById('books_list');
@isabloCh you don't need axios to pass the prop. You can extract data from data attribute in `application_vue.js` and pass it to this component. Next time you can implement axios.

2018-04-18 15:53 UTC, isabloCh commented on app/javascript/packs/application_vue.js
> +    render: h => h(BooksList)
I can do it this way
document.addEventListener('DOMContentLoaded', () => {
  new Vue({
    el: '#books_list',
    render: h => h(BooksList)
  })
})

?

2018-04-18 15:59 UTC, resivalex commented on app/javascript/packs/application_vue.js
> +    render: h => h(BooksList)
зачем `render`? пример выше тебе не нравится?

2018-04-19 09:50 UTC, resivalex commented on app/javascript/packs/application_vue.js
> +    render: h => h(BooksList)
@isabloCh swears, that it doesn't work. let him do with `render`

2018-04-20 14:17 UTC, closed without merging